spring:
  application:
    name: admin_user
  #mysql数据库配置
  datasource:
    url: jdbc:mysql://10.0.0.210:3506/mkadmin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 100
      maxWait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      max-open-prepared-statements: 100
      filters: stat,wall,log4j2
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      use-global-data-source-stat: true

server:
  port: 2001

eureka:
  client:
    service-url:
       defaultZone: http://10.0.0.213:1001/eureka/
  instance:
    # 注册时使用ip而不是主机名
    prefer-ip-address: true
    # 注册名称显示IP和Port
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml








